notifications:
  email: false
dist: trusty
services:
  - docker
os:
  - linux
before_install:
 - mkdir $HOME/video
 - ls -la
 - pwd
 - docker build -t m5tube -f .travis.DockerFile .
#env:
#   - VIDEOTITLE='TestVideo'
#   - VIDEOPATH='/usr/src/M5Tube/video/test.mp4'
script: >
  docker run -ti --rm
  -v $HOME/video:/usr/src/M5Tube/video
  -w /usr/src/M5Tube m5tube bash -c "PATH=$PATH:/usr/src/M5Tube/workflow.sh $VIDEOTITLE $VIDEOPATH"
